### ISSUE TITLE
Switch locale.

### ISSUE THREAD

**Issue by philipbaginski** [marshmallow-packages/translatable#27]
I installed packeage and it works proper. But where is no way to change locale - like drop down with list of languages. Any idea how to make it?

**Comment by stefvanesch** [comment]
@philipbaginski have you tried the example from the documentation?

```php
use Marshmallow\Translatable\Models\Language;
$languages = Language::get();

# In your blade file
@foreach($languages as $language)
	<a href="{{ route('set-locale', $language) }}">
		{{ $language->name }}
	</a>
@endforeach
```

**Comment by stefvanesch** [comment]
You can also get the language icon as shown in the example below. I will close this issue for now. If this doesnt work for you please let us know!

```php
<img src="{{ asset('storage/' . $language->icon) }}" alt="{{ $language->name }}">
```
